title: Nithish's Blog
description: >
  I write mostly about AI and software engineering.
url: "/"
paginate:	5 # The number of posts to show per page on your homepage
name: "Nithish Bolleddula"
email: 'nithish.bhu@gmail.com'
markdown: kramdown
twitter_image: assets/favicon/pphoto.png
permalink: none
kramdown:
  parse_block_html: true
plugins: [jekyll-paginate]
gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-sass-converter
  - jekyll-textile-converter
long_description: >
  I write about artificial intelligence (AI), technology, books, languages and some time random stuff.
real_url: https://nithish08.github.io